DROP SEQUENCE MEMBER_TB_SEQ;
DROP TRIGGER MEMBER_TB_TRG;
DROP TABLE MEMBER_TB;
DROP TABLE GRADE_TB;

CREATE TABLE MEMBER_TB (
	memberId	    NUMBER	                            CONSTRAINT PK_MEMBER_TB_ID PRIMARY KEY,
	gradeName       VARCHAR2(100)   DEFAULT 'GENERAL'   NOT NULL,
	memberReg   	DATE		    DEFAULT SYSDATE     NOT NULL,
	memberUnreg	    DATE,
	memberPwChange 	DATE	        DEFAULT SYSDATE     NOT NULL,
	memberAgree	    NUMBER(1)		DEFAULT 0           NOT NULL,
	memberRight	    NUMBER(1)       DEFAULT 0           NOT NULL,
	memberEmail	    VARCHAR2(100)                       NOT NULL,
	memberName	    VARCHAR2(100),
	memberNick  	VARCHAR2(100),
	memberPhone     VARCHAR2(100),
	memberGender    NUMBER(1),
	memberPassword	VARCHAR2(100),
	memberBirth 	DATE
);

CREATE TABLE GRADE_TB (
	gradeName       VARCHAR2(100)  	DEFAULT 'GENERAL'   CONSTRAINT PK_GRADE_TB_NAME PRIMARY KEY,
	gradeDiscount   NUMBER          DEFAULT 0	        NOT NULL
);

ALTER TABLE MEMBER_TB
ADD CONSTRAINT FK_MEMBER_TB FOREIGN KEY (gradeName) 
REFERENCES GRADE_TB(gradeName) ON DELETE CASCADE;

CREATE SEQUENCE MEMBER_TB_SEQ;

CREATE TRIGGER MEMBER_TB_TRG
BEFORE INSERT ON MEMBER_TB
FOR EACH ROW 
BEGIN
  BEGIN
    IF INSERTING AND :NEW.memberId IS NULL THEN
      SELECT MEMBER_TB_SEQ.NEXTVAL INTO :NEW.memberId FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
